(******************************************************************************

     DO NOT EDIT THIS FILE

******************************************************************************)

module HW10.MySolution

let dispatchOrder = function
  | RandomAIPlayerFirst ->
    TicTacToe(O, X, true, RandomStrategy ()).Run()
    true
  | RandomAIComputerFirst ->
    TicTacToe(O, X, false, RandomStrategy ()).Run()
    true
  | MinimaxAIPlayerFirst ->
    TicTacToe(O, X, true, MinimaxStrategy ()).Run()
    true
  | MinimaxAIComputerFirst ->
    TicTacToe(O, X, false, MinimaxStrategy ()).Run()
    true
  | Exit -> false

let rec gameLoop cont =
  if cont then GameMenu.takeOrder () |> dispatchOrder |> gameLoop
  else 0

[<EntryPoint>]
let main _args =
  printfn "[CS220] Tic Tac Toe"
  gameLoop true
